# Generated by Django 2.1.5 on 2022-03-17 18:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=128, unique=True)),
                ('movie_information', models.CharField(max_length=1000)),
                ('release_date', models.DateField()),
                ('movie_image', models.ImageField(upload_to='Movie_images')),
                ('slug', models.SlugField(default='abc')),
                ('trailer_link', models.URLField(default='/abc')),
            ],
        ),
        migrations.CreateModel(
            name='Movie_review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_content', models.CharField(max_length=2000)),
                ('likes_number', models.IntegerField()),
                ('dislikes_number', models.IntegerField()),
                ('create_time', models.DateField(auto_now_add=True)),
                ('grade', models.IntegerField(default=1.0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='rango.Movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.CharField(blank=True, max_length=512)),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
