# Generated by Django 2.1.5 on 2022-03-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=128, unique=True)),
                ('movie_information', models.CharField(max_length=512)),
                ('release_date', models.DateField()),
                ('movie_image', models.ImageField(upload_to='profile_images')),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
    ]
