# Generated by Django 2.1.5 on 2022-03-06 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20220306_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_content', models.CharField(max_length=256)),
                ('likes_number', models.IntegerField()),
                ('dislikes_number', models.IntegerField()),
                ('creat_time', models.DateField()),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.Movie')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.UserProfile')),
            ],
        ),
    ]
