# Generated by Django 2.1.5 on 2022-03-06 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0003_movie_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie_review',
            old_name='movie_id',
            new_name='movie',
        ),
        migrations.RenameField(
            model_name='movie_review',
            old_name='user_id',
            new_name='user',
        ),
    ]
